### ISSUE TITLE
[Compatibility] CompactUI Mod

### ISSUE THREAD

**Issue by ardissaps** [SpaceWalkerRS/no-resource-pack-warnings#1]
Red Warnings still appear with [CompactUI](https://www.curseforge.com/minecraft/mc-mods/compact-ui) installed.
![image](https://user-images.githubusercontent.com/82106625/177019791-c4103de6-5db3-4a54-8308-3eef998380ac.png)

**Comment by MrMelon54** [comment]
Opposite issue for [Compact UI #5](https://github.com/MrMelon54/compact-ui-fabric/issues/5)

**Comment by MrMelon54** [comment]
Fixed as of Compact UI v3.0.1

**Comment by SpaceWalkerRS** [comment]
Thanks for the report. I see it's already been fixed, so I'll close this issue.
