### ISSUE TITLE
Resource packs are getting reset on each restart

### ISSUE THREAD

**Issue by SplendidAlakey** [SpaceWalkerRS/no-resource-pack-warnings#4]
**MC** 1.19.2
**FL** 0.14.18
**NRW** 1.1.0

To reproduce:

1. Install the mod on either Fabric or Quilt
2. Install [this](https://www.curseforge.com/minecraft/texture-packs/sullys-peeves/files/4040585) resource pack and activate it
3. Restart the game
4. Check your resource packs - it's been deactivated and doing anything from this point onward will reload all resources

Logs: https://gist.github.com/SplendidAlakey/56f03367ee05556996261cb11216dc65

**Comment by SpaceWalkerRS** [comment]
Thanks for the report! Should be fixed in v1.1.1.
