### ISSUE TITLE
Support for datapack warnings?

### ISSUE THREAD

**Issue by Duranson1** [SpaceWalkerRS/no-resource-pack-warnings#5]
Really love this mod! Just wondering if it would be possible to also remove datapack warnings?

**Comment by SpaceWalkerRS** [comment]
Does it not already? The code this mod targets makes no distinction between resource packs and data packs so I think it should already remove warnings on the data pack screen too.

**Comment by Duranson1** [comment]
Oh yeah it does sorry for not checking lol I just figured it didn't. Up to you obviously but including it in the mod description might be nice for any others looking to disable datapack warnings.

**Comment by SpaceWalkerRS** [comment]
That's a good suggestion. Frankly, the description should have mentioned it from the start. I'll update it and hopefully avoid further confusion about it. Thanks!
